#!/bin/bash

FILE=`dirname $0`/README
MACHINE_TYPE=`uname -m`
export USER=`whoami`
TOP_MARGIN=30
RIGHT_MARGIN=20
SCREEN_WIDTH=$(xwininfo -root | sed -n 's/.*Width: //p')
SCREEN_HEIGHT=$(xwininfo -root | sed -n 's/.*Height: //p')
W=$(( $SCREEN_WIDTH / 2 - $RIGHT_MARGIN ))
H=$(( $SCREEN_HEIGHT - 2 * $TOP_MARGIN ))

clear

check_sudo()
{
	if (( $EUID != 0 ))
		then
			echo
			echo "WARNING:"
			echo "To use this script, you need to run it as sudo"
			echo "Please use: <sudo ./install>"
			echo
		exit
	fi
}

check_platform()
{
	if [ ${MACHINE_TYPE} != 'armv7l' ]
		then
			echo
			echo "WARNING:"
			echo "This program do not support this plattform"
			echo "Visit http://www.darkdefense.net/own/iothoneypot/supported"
			echo "Sorry..."
			echo
		exit
	fi
}

activate_ssh()
{
	(
		echo "20"; sleep 1
		systemctl enable ssh
		echo "50"; sleep 1
		echo "70"; sleep 1
		echo "90";
		systemctl start ssh
	) |
	(
		zenity 	--progress \
       			--width=300 \
       			--height=100 \
       			--title="SSH service" \
       			--text="Enabling and starting SSH service..." \
       			--percentage=0

		if [ "$?" = 1 ]
			then
        			zenity 	--error \
				      	--width=200 \
					--height=50 \
               				--text="Operation canceled."
		fi
	)
}

modify_ssh_port()
{
	NEW_PORT=$(zenity --scale --width=300 --title="New SSH port" --text="Please select the new port where the real SSH service will be listening" --min-value=1000 --max-value=65535 --value=1000 --step=1)
	sed -i 's/#Port/Port/g' /etc/ssh/sshd_config
	sed -i "s/Port.*/Port $NEW_PORT/g" /etc/ssh/sshd_config
	service ssh restart
	ss -tlpn | grep ssh | (zenity --text-info --title="SSH port confirmation" --width 1000
		if [ "$?" = 1 ]
			then modify_ssh_port
		fi
	)	
}

update_upgrade()
{
	(
		echo "10"; sleep 1
		apt-get update
		echo "30"; sleep 1
		echo "60"; sleep 1
		echo "90";
		apt-get -y upgrade
	) |
	(
		zenity 	--progress \
       			--width=300 \
       			--height=100 \
       			--title="Updating" \
       			--text="Updating and upgrading system..." \
       			--percentage=0

		if [ "$?" = 1 ]
			then
        			zenity 	--error \
				      	--width=200 \
					--height=50 \
               				--text="Update canceled."
		fi
	)
}

docker_install()
{
	(
		echo "10"; sleep 1
		curl -fsSL https://get.docker.com -o get-docker.sh
		echo "20"; sleep 1
		sh get-docker.sh
		echo "40"; sleep 1
		echo "60"; sleep 1
		usermod -aG docker pi
		echo "90";
		systemctl enable docker
	) |
	(
		zenity 	--progress \
       			--width=300 \
       			--height=100 \
       			--title="Docker installation" \
       			--text="Installing and configurind Docker..." \
       			--percentage=0

		if [ "$?" = 1 ]
			then
        			zenity 	--error \
				      	--width=200 \
					--height=50 \
               				--text="Update canceled."
		fi
	)
	sudo docker run hello-world | zenity --text-info --title="Testing Docker" --width 600
}

cowrie_install()
{
	(
		echo "10"; sleep 1
		apt install apt-utils
		echo "20"; sleep 1
		git clone https://github.com/cowrie/docker-cowrie.git
		echo "40"; sleep 1
		cd docker-cowrie
		echo "50"; sleep 1
		make all
		echo "60"; sleep 1
		docker build -t cowrie .
		echo "90";
		docker run -p 22:2222/tcp cowrie
	) |
	(
		zenity 	--progress \
       			--width=300 \
       			--height=100 \
       			--title="Cowrie installation" \
       			--text="Installing and configurind Cowrie..." \
       			--percentage=0

		if [ "$?" = 1 ]
			then
        			zenity 	--error \
				      	--width=200 \
					--height=50 \
               				--text="Update canceled."
		fi
	)
}

installation()
{
	#Raspberry Pi comes with SSH port deactivated by default
	activate_ssh

	#Modify SSH port
	modify_ssh_port

	#Update and upgrade function
	update_upgrade
	
	#Install and configure Docker
	docker_install
	
	#Install and configure Cowrie
	cowrie_install
		
}

installation_stop()
{
        zenity 	--info \
		--title="Stopped" \
		--text="More info:  http://www.darkdefense.net" \
		--width=300 \
		--height=100
}

installation_finished()
{
        zenity 	--info \
		--title="Finished!" \
		--text="Instalon successfully finished." \
		--width=300 \
		--height=100
}

initial_warning()
{
	zenity 	--text-info \
       		--title="README" \
       		--width=$W \
       		--height=$H \
       		--filename=$FILE \
       		--checkbox="I read and accept the terms."

	case $? in
    		0)
        		installation
			;;
    		1)
        		installation_stop
			;;
    		-1)
        		echo "An unexpected error has occurred."
			;;
	esac
}

#First, check if the script was run as sudo, and if platform is 64 bit. If not, exit.
check_sudo
check_platform

#Show the initial warning with general info and considerations of using the script
initial_warning

#Proccess completed successfully
installation_finished
echo
echo Done!
echo Check locally if SSH and TELNET ports are open with: nmap 127.0.0.1
echo Check from other device scanning the network (nmap u others) and trying to connect to SSH an Telnet ports.
echo
exit 0

#....PENDING...:
# - Complete exit, after Cancel button is pressed in any process.
